/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.twocity.swipeablelistview;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int min_lock=0x7f040002;
        public static final int min_swipe=0x7f040000;
        public static final int min_vert=0x7f040001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class integer {
        public static final int dim_animation_duration=0x7f030009;
        public static final int dismiss_animation_duration=0x7f030006;
        public static final int escape_animation_duration=0x7f030002;
        /** 
    <integer name="activity_slide_left_duration">475</integer>
    <integer name="activity_slide_right_duration">525</integer>
    <integer name="activity_collapse_duration">125</integer>
    <integer name="expand_cc_bcc_dur">150</integer>
    <integer name="fadein_cc_bcc_dur">150</integer>

    <integer name="dialog_animationDefaultDur">220</integer>
    <integer name="dialog_animationShortDur">150</integer>
    <integer name="shrink_animation_duration">350</integer>
    <integer name="slide_animation_duration">320</integer>
    <integer name="fade_in_animation_duration">350</integer>
    
         */
        public static final int fade_duration=0x7f030000;
        public static final int hide_animation_duration=0x7f030008;
        public static final int max_dismiss_velocity=0x7f030004;
        public static final int max_escape_animation_duration=0x7f030003;
        public static final int snap_animation_duration=0x7f030005;
        /**  Swipe constants 
         */
        public static final int swipe_escape_velocity=0x7f030001;
        public static final int swipe_scroll_slop=0x7f030007;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
